// SPDX-License-Identifier: Apache-2.0

import type { ListChromeCatalog } from '../list-chrome.js'

/** The Spanish list chrome, compiled from the es-ES.po source beside it. */
const catalog: ListChromeCatalog = {
	'': { lang: 'es-ES', 'plural-forms': 'nplurals=2; plural=(n != 1);' },
	'%1$d of %2$d Item': ['%1$d de %2$d elemento', '%1$d de %2$d elementos'],
	'%1$s, %2$s': ['%1$s, %2$s'],
	'%1$s: %2$s': ['%1$s: %2$s'],
	'%d Item': ['%d elemento', '%d elementos'],
	'%d Item selected': ['%d elemento seleccionado', '%d elementos seleccionados'],
	'%s, selected': ['%s, seleccionado'],
	'%s: <groupName />': ['%s: <groupName />'],
	'(no title)': ['(sin título)'],
	'<Name>%1$s between (inc): </Name><Value>%2$s and %3$s</Value>': [
		'<Name>%1$s entre (incl.): </Name><Value>%2$s y %3$s</Value>',
	],
	'<Name>%1$s contains: </Name><Value>%2$s</Value>': [
		'<Name>%1$s contiene: </Name><Value>%2$s</Value>',
	],
	"<Name>%1$s doesn't contain: </Name><Value>%2$s</Value>": [
		'<Name>%1$s no contiene: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s includes all: </Name><Value>%2$s</Value>': [
		'<Name>%1$s incluye todo: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s includes: </Name><Value>%2$s</Value>': [
		'<Name>%1$s incluye: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is after: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es después de: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is before: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es antes de: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is greater than or equal to: </Name><Value>%2$s</Value>': [
		'<Name>%1$s superior o igual a: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is greater than: </Name><Value>%2$s</Value>': [
		'<Name>%1$s mayor que: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is in the past: </Name><Value>%2$s</Value>': [
		'<Name>%1$s está en el pasado: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is less than or equal to: </Name><Value>%2$s</Value>': [
		'<Name>%1$s menor o igual a: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is less than: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es menor que: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is none of: </Name><Value>%2$s</Value>': [
		'<Name>%1$s no es ninguno de los siguientes: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is not: </Name><Value>%2$s</Value>': [
		'<Name>%1$s no es: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is on or after: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es o es después de: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is on or before: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es o es antes de: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is over: </Name><Value>%2$s</Value>': [
		'<Name>%1$s ha terminado: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s is: </Name><Value>%2$s</Value>': [
		'<Name>%1$s es: </Name><Value>%2$s</Value>',
	],
	'<Name>%1$s starts with: </Name><Value>%2$s</Value>': [
		'<Name>%1$s empieza por: </Name><Value>%2$s</Value>',
	],
	Actions: ['Acciones'],
	Activity: ['Actividad'],
	'Add filter': ['Añadir filtro'],
	After: ['Después'],
	'After (inc)': ['Después (incl.)'],
	Appearance: ['Apariencia'],
	'Automatically load more content as you scroll, instead of showing pagination links.': [
		'Carga automáticamente más contenido a medida que navegas, en lugar de mostrar enlaces de paginación.',
	],
	Before: ['Antes'],
	'Before (inc)': ['Antes (incl.)'],
	'Between (inc)': ['Entre (incl.)'],
	Cancel: ['Cancelar'],
	Close: ['Cerrar'],
	Conditions: ['Condiciones'],
	Contains: ['Contiene'],
	'Coordinated Universal Time': ['Hora universal coordinada'],
	'Current page': ['Página actual'],
	'Date calendar': ['Calendario de fechas'],
	'Date range calendar': ['Calendario de rango de fechas'],
	'Date time': ['Fecha y hora'],
	Density: ['Densidad'],
	'Density option for DataView layout\u0004Balanced': ['Equilibrado'],
	'Density option for DataView layout\u0004Comfortable': ['Cómodo'],
	'Density option for DataView layout\u0004Compact': ['Compacto'],
	'Deselect all': ['Anular selección de todo'],
	"Doesn't contain": ['No contiene'],
	'Enable infinite scroll': ['Activar el desplazamiento infinito'],
	False: ['Falso'],
	'Filter by: %1$s': ['Filtrar por: %1$s'],
	'Greater than': ['Mayor que'],
	'Greater than or equal': ['Superior a o igual'],
	Grid: ['Cuadrícula'],
	'Hide column': ['Ocultar columna'],
	'In the past': ['En el pasado'],
	Includes: ['Incluye'],
	'Includes all': ['Incluye todos'],
	'Insert left': ['Insertar a la izquierda'],
	'Insert right': ['Insertar a la derecha'],
	Is: ['Es'],
	'Is none of': ['No es ninguno de'],
	'Is not': ['No es'],
	'Items per page': ['Elementos por página'],
	Layout: ['Estructura'],
	'Less than': ['Menor que'],
	'Less than or equal': ['Inferior a o igual'],
	List: ['Lista'],
	'List of: %1$s': ['Lista de: %1$s'],
	'Move left': ['Mover a la izquierda'],
	'Move right': ['Mover a la derecha'],
	'Navigate to item': ['Navegar hasta el elemento'],
	'Navigation bar': ['Barra de navegación'],
	'Next month': ['Mes siguiente'],
	'Next page': ['Página siguiente'],
	'No elements found': ['No se han encontrado elementos'],
	'No results': ['No hay resultados'],
	'No results found': ['No se encontraron resultados'],
	'Not on': ['No el'],
	On: ['El'],
	Optional: ['Opcional'],
	Order: ['Orden'],
	'Original aspect ratio': ['Proporción original'],
	Over: ['Hace más de'],
	'Page %1$d of %2$d': ['Página %1$d de %2$d'],
	'Preview size': ['Tamaño de la vista previa'],
	'Previous month': ['Mes anterior'],
	'Previous page': ['Página anterior'],
	Properties: ['Propiedades'],
	Remove: ['Eliminar'],
	Required: ['Obligatorio'],
	Reset: ['Restablecer'],
	'Reset search': ['Restablecer la búsqueda'],
	'Reset view': ['Restablecer vista'],
	'Row %d': ['Fila %d'],
	Search: ['Buscar'],
	'Search items': ['Buscar elementos'],
	'Select all': ['Seleccionar todo'],
	'Sort ascending': ['Orden ascendente'],
	'Sort by': ['Ordenar por'],
	'Sort descending': ['Orden descendente'],
	'Starts with': ['Empieza con'],
	Table: ['Tabla'],
	'Timezone: %s': ['Zona horaria: %s'],
	'Today, %s': ['Hoy, %s'],
	'Today, %s, selected': ['Hoy, %s, seleccionado'],
	True: ['Verdadero'],
	'Unknown status for %1$s': ['Estado desconocido para %1$s'],
	'View is used as a noun\u0004View options': ['Ver opciones'],
	'paging\u0004<div>Page</div>%1$s<div>of %2$d</div>': ['<div>Página</div>%1$s<div>de %2$d</div>'],
	'verb\u0004Filter': ['Filtrar'],
}

export default catalog
